---
- name: Configure server and deploy apps with Docker Compose
  hosts: webservers
  become: yes

  vars:
    project_path: /home/ubuntu/devops-modern-end-to-end-deployment

  tasks:

    - name: Update apt packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install required packages
      apt:
        name:
          - docker.io
          - docker-compose
          - git
          - openjdk-17-jdk
          - maven
        state: present

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Reset SSH connection (apply docker group)
      meta: reset_connection

    - name: Clone project repository
      git:
        repo: "https://github.com/akubukojaphet/devops-modern-end-to-end-deployment.git"
        dest: "{{ project_path }}"
        version: main
        force: yes

    - name: Build and run apps using Docker Compose
      command: docker-compose up -d --build
      args:
        chdir: "{{ project_path }}"
