name: DevOps Modern End-to-End CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  devops-pipeline:
    name: Build, Validate and Test Deployment
    runs-on: ubuntu-latest

    steps:
      # =========================
      # Checkout Code
      # =========================
      - name: Checkout source code
        uses: actions/checkout@v4

      # =========================
      # Build Java App
      # =========================
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build Java application
        working-directory: java-app
        run: mvn clean package -DskipTests

      # =========================
      # Docker Validation
      # =========================
      - name: Validate Docker Compose
        run: docker compose config

      - name: Build Docker images
        run: |
          docker build -t japhtech/japhet-portfolio:latest ./portfolio-app
          docker build -t japhtech/japhet-java-app:latest ./java-app

      # =========================
      # Run Containers
      # =========================
      - name: Run applications
        run: docker compose up -d --build

      - name: Show running containers
        run: docker ps

      # =========================
      # Verify Apps
      # =========================
      - name: Verify Portfolio App
        run: |
          sleep 15
          curl -f http://localhost:8081 || exit 1

      - name: Verify Java Container
        run: |
          sleep 20
          docker ps
          echo "Java container running"

      - name: Stop containers
        if: always()
        run: docker compose down

      # =========================
      # Terraform Validation
      # =========================
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Validate Terraform
        working-directory: terraform
        run: |
          terraform fmt -check
          terraform init -backend=false
          terraform validate

      # =========================
      # Ansible Validation
      # =========================
      - name: Install Ansible
        run: pip install ansible

      - name: Validate Ansible
        working-directory: ansible
        run: ansible-playbook --syntax-check deploy.yml

      # =========================
      # Kubernetes Validation
      # =========================
      - name: Validate Kubernetes manifests
        run: kubectl apply --dry-run=client -f k8s/
